name: abhinav-singh-portfolio

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup Pages
        uses: aws-actions/configure-aws-credentials@v1

    
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to GitHub Pages
        run: aws s3 sync . s3://abhinav-singh-portfolio --delete
